# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CbObjects',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=16)),
                ('entity_id', models.BigIntegerField()),
                ('parent_id', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('permalink', models.CharField(max_length=255)),
                ('category_code', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('founded_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=64, null=True)),
                ('homepage_url', models.CharField(blank=True, max_length=64, null=True)),
                ('twitter_username', models.CharField(blank=True, max_length=64, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_width', models.IntegerField(blank=True, null=True)),
                ('logo_height', models.IntegerField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('tag_list', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=64, null=True)),
                ('state_code', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('first_investment_at', models.DateField(blank=True, null=True)),
                ('last_investment_at', models.DateField(blank=True, null=True)),
                ('investment_rounds', models.IntegerField(blank=True, null=True)),
                ('invested_companies', models.IntegerField(blank=True, null=True)),
                ('first_funding_at', models.DateField(blank=True, null=True)),
                ('last_funding_at', models.DateField(blank=True, null=True)),
                ('funding_rounds', models.IntegerField(blank=True, null=True)),
                ('funding_total_usd', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('first_milestone_at', models.DateField(blank=True, null=True)),
                ('last_milestone_at', models.DateField(blank=True, null=True)),
                ('milestones', models.IntegerField(blank=True, null=True)),
                ('relationships', models.IntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cb_objects',
                'managed': False,
            },
        ),
    ]
