SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '7522okfvc7gkp8'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'dQqSsfyiW0H7a2BP'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/login'
LINKEDIN_SCOPE = ['r_basicprofile']